config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:index, :show] do
    resources :groups, only: [ :new, :create, :show, :destroy ] do
      resources :purchases, only: [ :new, :create, :destroy ]
    end
  end
  
  root to: "splashes#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: "splash#index"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :purchasegroups, dependent: :destroy
  has_many :purchases, through: :purchasegroups, dependent: :destroy

  validates :name, presence: true, length: { in: 3..15 }
  validates :icon, presence: true

  def self.total_purchased(group_id)
    sum = 0
    purchase_groups = PurchaseGroup.all
    purchase_groups.each do |purchase_group|
      next unless purchase_group.group_id == group_id.to_i

      purchases = Purchase.where(id: purchase_group.purchase_id)
      purchases.each do |purchase|
        sum += purchase.amount.to_i
      end
    end
    sum
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups/1 or /groups/1.json
  def show
    @groups = Group.where(user_id: current_user.id)
    @purchase_groups = PurchaseGroup.all.order(created_at: :desc)
  end

  # GET /groups/new
  def new
    @groups = Group.all
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(
      user_id: group_params[:user_id],
      name: group_params[:name],
      icon: group_params[:icon]
    )

    respond_to do |format|
      if @group.save
        format.html { redirect_to user_path(current_user.id), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= group.icon %>
  </p>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
    <p>
      <%= link_to "Show this group", group %>
    </p>
  <% end %>
</div>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<nav class="relative flex flex-wrap items-center justify-between w-full py-4 shadow-lg  bg-main">
  <div class="flex flex-wrap items-center justify-center w-full px-6 container-fluid">
    <div class="space-x-9 container-fluid">
      <a class="mt-2 -mx-7 lg:mt-0" href="#">
      <%= link_to '←', user_path(current_user.id), class:'text-light text-decoration-none text-xl hover:text-text focus:text-text' %>
        <span class="font-medium text-light">NEW PURCHASE TYPE</span>
        <span class="font-medium"><%= link_to 'Next',{}, class: 'text-light text-m text-decoration-none hover:text-text focus:text-text'%></span>
      </a>
    </div>
  </div>
</nav>

<div class= 'flex flex-col items-center justify-center mt-4 space-y-6'>
  <div class='w-70'>
    <%=form_with model: @group, url: user_groups_path,   scope: :group do |form| %>
      <%= form.label 'Choose a Purchase Type', class: 'text-text font-medium' %>
      <%= form.select :icon, options_for_select([
      ['Motorcycle', 'https://res.cloudinary.com/webdevjunior/image/upload/v1660236819/Budget%20App/motorcycle_xyzxbu.png'],
      ['Home', 'https://res.cloudinary.com/webdevjunior/image/upload/v1660236818/Budget%20App/home_byzqxg.png'],
      ['Travel', 'https://res.cloudinary.com/webdevjunior/image/upload/v1660236819/Budget%20App/travel_jawboh.png'],
      ['Tech', 'https://res.cloudinary.com/webdevjunior/image/upload/v1660237665/Budget%20App/tech_q9qlqi.png'],
      ['Clothing', 'https://res.cloudinary.com/webdevjunior/image/upload/v1660237228/Budget%20App/clothing_ljsdqf.png'],
      ['Training', 'https://res.cloudinary.com/webdevjunior/image/upload/v1660237546/Budget%20App/training_jvkxte.png'],
      ['Food', 'https://res.cloudinary.com/webdevjunior/image/upload/v1660237227/Budget%20App/food_symnnx.png']
      ]), {}, class:'px-4 flex items-center w-72 rounded  transition duration-300 ease-in-out text-heading text-base focus:outline-none focus:ring-0 border border-border-base focus:border-accent h-10 my-4', id: 'icon', aria_label: 'purchase'%>
      <%= form.hidden_field :user_id, value: current_user.id  %>
      <div>
        <%= form.label :name, class: 'text-text font-medium'%>
        <%= form.text_field :name, class: 'px-4 flex items-center w-72 rounded  transition duration-300 ease-in-out text-heading text-base focus:outline-none focus:ring-0 border border-border-base focus:border-accent h-10' %>
      </div>
      <div class='h-12 p-4 my-4 font-semibold leading-none text-white transition duration-300 ease-in-out border border-transparent rounded outline-none cursor-auto bg-main max-w-fit focus:outline-none focus:shadow focus:ring-1 focus:ring-accent-700 bg-accent hover:bg-primary'>
        <%= form.submit 'Add Purchase Type'%>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<nav class="fixed flex flex-wrap items-center justify-between block w-full py-4 mb-4 shadow-lg bg-main">
  <div class="flex flex-wrap items-center justify-center w-full px-6 container-fluid">
    <div class="space-x-16 container-fluid">
      <a class="mt-2 -mx-7 lg:mt-0" href="#">
      <%= link_to '←', user_path(current_user.id), class:'text-light text-decoration-none text-xl hover:text-text focus:text-text h-2 w-2' %>
        <span class="font-medium text-light">PURCHASED</span>
        <span class="font-medium"><%= link_to 'Next',{}, class: 'text-light text-m text-decoration-none hover:text-text focus:text-text'%></span>
      </a>
    </div>
  </div>
</nav>

<div class='flex flex-col items-center block mx-auto text-sm '>
<div class='sticky mt-20 top-20'>
<% @groups.each do |group| %>
  <% if group.id == params[:id].to_i %>
    <div class='flex flex-row items-center justify-between py-3 space-x-4 in w-75'>
      <div><%= image_tag group.icon, class:'h-10 w-10' %>
      </div>
      <span><code class='text-2px text-second'><%= group.name %></code> total purchased: <code class='text-danger'>$</code><%= Group.total_purchased(params[:id]) %>
      </span>
    <% end %>
  <% end %>
 </div>
</div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<div class='sticky bottom-0 flex flex-col items-center justify-center block h-64 space-y-6'>
  <div class='flex flex-col block overflow-auto h-62'>
    <% @purchase_groups.each do |purchase_group| %>
     <% if purchase_group.group_id == params[:id].to_i %>
     <% purchases = Purchase.where(id: purchase_group.purchase_id) %>
     <% purchases.each do |purchase| %>
      <div class = 'block p-6 my-1 bg-white rounded-lg shadow-lg'>
        <div class= 'flex flex-row justify-between w-64 space-x-3'>
          <p class= 'mb-2 text-xl font-medium leading-tight text-gray-900'><%= purchase.name %></p>
          <p> $<%= purchase.amount %></p>
        </div>
        <div class= ''>
          <p>Date: <%=((purchase.created_at).to_s)[0,10] %></p>
        </div>
       <% end %>
       </div>
      <% end %>
    <% end %> 
    <br />
    
</div>
  <div class= 'sticky top-0 flex flex-row items-center justify-center py-3 space-x-4 h-14 w-80 bg-second'>
    <div class= ''>
      <div class= 'text-center'><%= link_to 'Add new purchase', new_user_group_purchase_path(current_user.id, params[:id]), class: 'inline-block px-6 py-2.5 text-white font-medium text-xs leading-tight uppercase shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out border-2 border-light-blue-500 border-opacity-100 w-72'%>
      </div>
     </div>
  </div>
</div>