config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:index, :show] do
    resources :groups, only: [ :new, :create, :show, :destroy ] do
      resources :purchases, only: [ :new, :create, :destroy ]
    end
  end
  
  root to: "splashes#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: "splash#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchases, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, length: { in: 3..15 }
  validates :email, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index; end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @groups = Group.where(user_id: params[:id])
  end

  # GET /users/1/edit
  def edit; end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= user.id %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
 
    <%= render partial: "user", locals: {user: @user} %>
    <p>
      <%= link_to "Show this user", @user %>
    </p>

</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<nav class="relative sticky top-0 flex flex-wrap items-center justify-between w-full py-4 shadow-lg overscroll-auto bg-main">
  <div class="flex flex-wrap items-center justify-center w-full px-6 container-fluid">
    <div class="container-fluid">
      <a class="mt-2 space-x-14 -mx-7 lg:mt-0" href="#">
        <svg class='inline w-5 h-5 text-light text-decoration-none hover:text-text focus:text-text' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) --><path fill="#ecedee" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"/></svg>
        <span class="font-medium text-light">PURCHASE TYPES</span>
        <svg class='inline w-5 h-5'xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) --><path fill="#ecedee" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"/></svg>
      </a>
    </div>
  </div>
</nav>


<div class= 'flex flex-col items-center justify-center space-y-6' >
  <div class='flex flex-row items-center justify-between block max-w-sm p-6 py-3 space-x-10 bg-white rounded-lg shadow-lg w-75'>
    <div class='font-medium text-text'>
      <span>Welcome <span class= 'font-medium text-danger'>Saver</span> <%= @user.name %></span>
    </div>
    <div class='h-12 p-4 my-4 font-semibold leading-none text-white transition duration-300 ease-in-out border border-transparent rounded outline-none cursor-auto bg-main max-w-fit focus:outline-none focus:shadow focus:ring-1 focus:ring-accent-700 bg-accent hover:bg-primary'>
      <%= button_to 'Logoff', destroy_user_session_path,  method: :delete %>
    </div>
  </div>

</div>

<div class='flex flex-col items-center justify-center space-y-6'>  
  <div class='flex flex-col items-center justify-center'>
    <% @groups.each do |group| %>
       <div class= 'flex items-center justify-between h-20 p-2 py-3 my-1 bg-white border-2 rounded-lg shadow-lg border-light w-80'>
          <div class='flex flex-row items-center space-x-14'>
            <%= image_tag group.icon, class: 'h-10 w-10' %>
            <%= link_to group.name, user_group_path(current_user.id, group.id), class: 'text-2px text-second' %>
          </div>
          <div><span class='text-danger'>$</span><%= Group.total_purchased(group.id)%>
          </div>
      </div>
    <% end %>
  </div>
  

      <div class='flex flex-row items-center justify-center py-3 space-x-4 text-center h-14 w-80 bg-second'>
        <%= link_to 'Add Purchase Type', new_user_group_path(params[:id]), class:'inline-block px-6 py-2.5 text-white font-medium text-xs leading-tight uppercase shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out border-2 border-light-blue-500 border-opacity-100 w-72' %>
      </div>
</div>
</div>