config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:index, :show] do
    resources :groups, only: [ :new, :create, :show, :destroy ] do
      resources :purchases, only: [ :new, :create, :destroy ]
    end
  end
  
  root to: "splashes#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root to: "splash#index"
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[show edit update destroy]

  # GET /purchases or /purchases.json
  def index
    @purchases = Purchase.includes(:user).where(user: current_user)
  end

  # GET /purchases/1 or /purchases/1.json
  def show
    @purchase = Purchase.includes(:user).find(params[:id])
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit; end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.new(
      name: purchase_params[:name],
      amount: purchase_params[:amount],
      user_id: current_user.id
    )

    respond_to do |format|
      if @purchase.save
        save_purchase_group(@purchase)
        format.html do
          redirect_to user_group_path(current_user.id, purchase_params[:group_id]),
                      notice: 'Purchase was successfully created.'
        end

        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to purchase_url(@purchase), notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  def save_purchase_group(purchase)
    @purchase_group = PurchaseGroup.create!(
      purchase_id: purchase.id,
      group_id: purchase_params[:group_id]
    )
  end

  # Only allow a list of trusted parameters through.
  def purchase_params
    params.require(:purchase).permit(:name, :amount, :group_id)
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>">
  <p>
    <strong>Name:</strong>
    <%= purchase.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= purchase.amount %>
  </p>

</div>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Purchases</h1>

<div id="purchases">
  <% @purchases.each do |purchase| %>
    <%= render purchase %>
    <p>
      <%= link_to "Show this purchase", purchase %>
    </p>
  <% end %>
</div>

<%= link_to "New purchase", new_purchase_path %>

app/views/purchases/new.html.erb
<nav class="relative flex flex-wrap items-center justify-between w-full py-4 shadow-lg bg-main">
  <div class="flex flex-wrap items-center justify-center w-full px-6 container-fluid">
    <div class="space-x-9 container-fluid">
      <a class="mt-2 -mx-7 lg:mt-0" href="#">
      <%= link_to '←', user_path(current_user.id), class:'text-light text-decoration-none text-xl hover:text-text focus:text-text' %>
        <span class="font-medium text-light">NEW PURCHASE</span>
        <span class="font-medium"><%= link_to 'Next',{}, class: 'text-light text-m text-decoration-none hover:text-text focus:text-text'%></span>
      </a>
    </div>
  </div>
</nav>


<div class= 'flex flex-col items-center justify-center mt-4 space-y-6'>
  <div class='w-70'>
  <%=form_with model: @purchase, url: user_group_purchases_path, scope: :purchase do |form| %>
  <%= form.label :name, 'Purchase name', class: 'text-text font-medium' %>
  <%= form.text_field :name, class:'px-4 flex items-center w-72 rounded  transition duration-300 ease-in-out text-heading text-base focus:outline-none focus:ring-0 border border-border-base focus:border-accent h-10 my-4', require: true, autofocus: true %>
  <%= form.label :amount, class: 'text-text font-medium' %>
  <%= form.text_field :amount, class:'px-4 flex items-center w-72 rounded  transition duration-300 ease-in-out text-heading text-base focus:outline-none focus:ring-0 border border-border-base focus:border-accent h-10 my-4', require: true, autofocus: true %>


  <div class="dropdown-toggle
         px-2 w-72 flex space-x-1 py-1.5 bg-second text-text font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out items-center whitespace-nowrap">
        <%= form.label :purchase, 'Assign to Purchase Type', class: 'text-white' %><br />
        <%= form.collection_select :group_id, Group.where(user_id: current_user.id).order(:name), :id, :name %>
  </div>
  <br />


  <div class= 'h-12 p-4 font-semibold leading-none text-white transition duration-300 ease-in-out border border-transparent rounded outline-none cursor-pointer bg-main max-w-fit focus:outline-none focus:shadow focus:ring-1 focus:ring-accent-700 bg-accent hover:bg-primary'>
    <%= form.submit 'Add Purchase', class: 'cursor-pointer' %>
  </div>

    <% end %>
</div>

app/views/purchases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase %>

<div>
  <%= link_to "Edit this purchase", edit_purchase_path(@purchase) %> |
  <%= link_to "Back to purchases", purchases_path %>

  <%= button_to "Destroy this purchase", @purchase, method: :delete %>
</div>